name: Cypress Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  magellan:
    env:
      CI: true
    strategy:
      matrix:
        node: [1, 2, 3, 4, 5, 6]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: xvfb-run --auto-servernum npm run cypress:verify
      - run: npm run magellan -- --bucket=${{ matrix.node }}/6 --max_workers=2 --max_test_attempts=1
      - uses: bcomnes/cleanup-xvfb@v1
  # cypress:
  #   env:
  #     CI: true
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: bahmutov/npm-install@v1
  #     - run: npm run cypress:verify
  #     - run: npm run cypress
